### ISSUE TITLE
Feed Fetch Error , caused by Google Feed API was deprecated.

### ISSUE THREAD

**Issue by miyabi-answer** [siddii/angular-feeds#19]
>TypeError: Cannot read property 'Feed' of undefined
>    at Object.getFeeds (http://cthulhu.sessi.onl/new2/lib/angular-feeds/app/angular-feeds/angular-feeds.js:82:34)
>    at new controller (http://cthulhu.sessi.onl/new2/lib/angular-feeds/app/angular-feeds/angular-feeds.js:39:19)
>    at Object.invoke (http://cthulhu.sessi.onl/new2/lib/ionic/js/ionic.bundle.js:17630:17)
>    at extend.instance (http://cthulhu.sessi.onl/new2/lib/ionic/js/ionic.bundle.js:22179:34)
>    at nodeLinkFn (http://cthulhu.sessi.onl/new2/lib/ionic/js/ionic.bundle.js:21289:36)
>    at compositeLinkFn (http://cthulhu.sessi.onl/new2/lib/ionic/js/ionic.bundle.js:20721:13)
>    at compositeLinkFn (http://cthulhu.sessi.onl/new2/lib/ionic/js/ionic.bundle.js:20725:13)
>    at nodeLinkFn (http://cthulhu.sessi.onl/new2/lib/ionic/js/ionic.bundle.js:21325:24)
>    at compositeLinkFn (http://cthulhu.sessi.onl/new2/lib/ionic/js/ionic.bundle.js:20721:13)
>    at nodeLinkFn (http://cthulhu.sessi.onl/new2/lib/ionic/js/ionic.bundle.js:21325:24) <ion-nav-view name="tab-dash" class="view-container tab-content" nav-view="active" nav-view-transition="ios">

**Comment by devfxplayer** [comment]
any update on this?

**Comment by SamMurray381** [comment]
I've currently picked up a project that has this issue too, so would be great if there was a fix.

**Comment by DMDc0de** [comment]
maybe a duplicate of [#25](https://github.com/siddii/angular-feeds/issues/25l)
